name: Deploy to GCP VM

on:
  push:
    branches:
      - main # or whichever branch you want to auto-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > sa_key.json
          gcloud auth activate-service-account --key-file=sa_key.json

          gcloud compute scp ./server/ clip-sync-gpt:~/ --recurse --zone=us-west4-a --project "clipsyncgpt"

          # SCP the deployment script
          gcloud compute scp ./deploy.sh clip-sync-gpt:~/ --zone=us-west4-a --project "clipsyncgpt"

          # SSH into the VM and run the deployment script
          gcloud compute ssh clip-sync-gpt --zone=us-west4-a --project "clipsyncgpt" --command="bash ~/deploy.sh"
