name: Deploy to GCP VM

on:
  push:
    branches:
      - main # or whichever branch you want to auto-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > sa_key.json
          gcloud auth activate-service-account --key-file=sa_key.json

          # Copy the 'server' directory to the GCP VM
          gcloud compute scp ./server/ clip-sync-gpt:~/ --recurse --zone=us-west4-a --project "clipsyncgpt"

          # SSH into the VM and run commands sequentially
          gcloud compute ssh clip-sync-gpt --zone=us-west4-a --project "clipsyncgpt" << EOF
          cd ~/server
          pwd
          pm2 ls
          if pm2 info clip-sync-server > /dev/null 2>&1; then 
            pm2 restart clip-sync-server --update-env; 
          else 
            pm2 start index.js --name clip-sync-server; 
          fi
          EOF
