name: Deploy to GCP VM

on:
  push:
    branches:
      - main # or whichever branch you want to auto-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > sa_key.json
          gcloud auth activate-service-account --key-file=sa_key.json

          # Copy the 'server' directory to the GCP VM
          gcloud compute scp ./server/ clip-sync-gpt:~/ --recurse --zone=us-west4-a --project "clipsyncgpt"

          # SSH into the VM, change the working directory to 'server' and restart the server using pm2
          gcloud compute ssh clip-sync-gpt --command="cd ~/server && pm2 restart clip-sync-server" --zone=us-west4-a --project "clipsyncgpt"
