name: Deploy to GCP VM

on:
  push:
    branches:
      - main # or whichever branch you want to auto-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > sa_key.json
          gcloud auth activate-service-account --key-file=sa_key.json
          # Assuming you're deploying using gcloud, adjust the below command accordingly
          gcloud compute scp -r ./server/ clip-sync-gpt:~/server --zone=us-west4-a --project "clipsyncgpt"
          gcloud compute ssh clip-sync-gpt --command="cd ~/server && pm2 restart clip-sync-server" --zone=us-west4-a --project "clipsyncgpt"
